In [14]:
import cv2
import numpy as np
from PIL import Image

noise = np.zeros([256, 192, 1], dtype=np.uint8)
### noise
noise = cv2.randn(noise, 0, 255)
print(noise)
print(noise.shape)
cv2.imwrite('shape.jpg', noise)

img = Image.fromarray(noise, 'RGB')
img.save('shape.jpg')

[[[238]
  [  0]
  [  0]
  ...
  [255]
  [249]
  [  0]]

 [[  0]
  [  0]
  [255]
  ...
  [  0]
  [  0]
  [ 98]]

 [[211]
  [255]
  [210]
  ...
  [  0]
  [ 29]
  [  0]]

 ...

 [[ 91]
  [  0]
  [  0]
  ...
  [  0]
  [  0]
  [  0]]

 [[255]
  [224]
  [  0]
  ...
  [  0]
  [113]
  [  0]]

 [[  7]
  [217]
  [255]
  ...
  [  0]
  [  0]
  [  0]]]
(256, 192, 1)


ValueError: not enough image data